# SPDX-FileCopyrightText: 2024 Soulfind Contributors
# SPDX-License-Identifier: GPL-3.0-or-later

version = 1

[[annotations]]
path = ["dub.*"]
SPDX-FileCopyrightText = "2024 Soulfind Contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"
