# SPDX-FileCopyrightText: 2024 Soulfind Contributors
# SPDX-License-Identifier: GPL-3.0-or-later

name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    container: alpine:edge
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - compiler: dmd
            ccommand: dmd
          - compiler: ldc
            ccommand: ldmd2
    env:
      DC: ${{ matrix.ccommand }}
      DEBUG: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: apk add ${{ matrix.compiler }} make musl-dev sqlite-dev

      - name: Build
        run: make

  artifacts:
    runs-on: ubuntu-latest
    container: alpine:edge
    timeout-minutes: 15
    strategy:
      matrix:
        arch: [x86_64]
        type: [release, debug]
    env:
      DC: ldmd2 -static -O
      DEBUG: ${{ matrix.type == 'debug' && '1' || '0' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: apk add ldc ldc-static make musl-dev sqlite-dev sqlite-static

      - name: Build
        run: make

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: soulfind-${{ matrix.arch }}-linux-${{ matrix.type }}
          path: bin
