# SPDX-FileCopyrightText: 2024 Soulfind Contributors
# SPDX-License-Identifier: GPL-3.0-or-later

name: CI

on: [push, pull_request]

jobs:

  reuse-compliance:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: REUSE compliance
        uses: fsfe/reuse-action@v5

  build:
    timeout-minutes: 15
    strategy:
      matrix:
        image: [ubuntu-latest, macos-latest]
        arch: [x86_64, arm64]
        compiler: [dmd, ldc]
        type: [release, debug]
        include:
          - image: ubuntu-latest
            container: alpine:edge

          - image: ubuntu-latest
            arch: x86_64
            target: x86_64-linux-musl

          - image: macos-latest
            arch: x86_64
            target: x86_64-apple-macos10.12

          - image: macos-latest
            arch: arm64
            target: arm64-apple-macos11.0

          - compiler: dmd
            target: x86_64

          - compiler: ldc
            image: ubuntu-latest
            dflags: -static

          - type: debug
            flags: --debug=db --debug=msg --debug=user
        exclude:
          - image: ubuntu-latest
            arch: arm64

          - compiler: dmd
            arch: arm64
    runs-on: ${{ matrix.image }}
    container: ${{ matrix.container }}
    env:
      DFLAGS: ${{ matrix.dflags }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: apk add ${{ matrix.compiler }} dub gcc musl-dev sqlite-static

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        uses: dlang-community/setup-dlang@v2
        with:
          compiler: ${{ matrix.compiler }}

      - name: Build
        run: dub build --build=${{ matrix.type }} --arch=${{ matrix.target }} ${{ matrix.flags }}

      - name: Linting
        run: dub lint

      - name: Archive artifacts
        if: matrix.compiler == 'ldc'
        uses: actions/upload-artifact@v4
        with:
          name: soulfind-${{ matrix.arch }}-${{ runner.os }}-${{ matrix.type }}
          path: bin
