# SPDX-FileCopyrightText: 2024 Soulfind Contributors
# SPDX-License-Identifier: GPL-3.0-or-later

name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    container: alpine:edge
    timeout-minutes: 15
    strategy:
      matrix:
        arch: [x86_64]
        compiler: [dmd, ldc]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: apk add ${{ matrix.compiler }} dub gcc musl-dev reuse sqlite-dev

      - name: REUSE compliance
        run: reuse lint

      - name: Build
        run: dub build

      - name: Linting
        run: dub lint

  artifacts:
    timeout-minutes: 15
    strategy:
      matrix:
        image: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86_64]
        type: [release, debug]
        include:
          - image: ubuntu-latest
            container: alpine:edge
            os: linux
            dflags: -static
          - image: macos-latest
            os: macos
          - image: windows-latest
            os: windows
          - type: debug
            flags: --debug=db --debug=msg --debug=user
    runs-on: ${{ matrix.image }}
    container: ${{ matrix.container }}
    env:
      DFLAGS: ${{ matrix.dflags }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: matrix.os == 'linux'
        run: apk add dub gcc ldc musl-dev sqlite-static

      - name: Install dependencies (macOS/Windows)
        if: matrix.os != 'linux'
        uses: dlang-community/setup-dlang@v2
        with:
          compiler: ldc

      - name: Build
        run: dub build --build=${{ matrix.type }} ${{ matrix.flags }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: soulfind-${{ matrix.arch }}-${{ matrix.os }}-${{ matrix.type }}
          path: bin
