# SPDX-FileCopyrightText: 2024 Soulfind Contributors
# SPDX-License-Identifier: GPL-3.0-or-later

name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    container: alpine:edge
    timeout-minutes: 15
    strategy:
      matrix:
        arch: [x86_64]
        compiler: [dmd, ldc]
        include:
          - compiler: dmd
            ccommand: dmd
          - compiler: ldc
            ccommand: ldc2
    env:
      DC: ${{ matrix.ccommand }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: apk add ${{ matrix.compiler }} dub gcc musl-dev sqlite-dev

      - name: Build
        run: dub build

      - name: Linting
        run: dub lint

  artifacts:
    runs-on: ubuntu-latest
    container: alpine:edge
    timeout-minutes: 15
    strategy:
      matrix:
        arch: [x86_64]
        type: [release, debug]
        include:
          - type: debug
            flags: --debug=db --debug=msg --debug=user
    env:
      DFLAGS: -static
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: apk add dub gcc ldc ldc-static musl-dev sqlite-dev sqlite-static

      - name: Build
        run: dub build --build=${{ matrix.type }} ${{ matrix.flags }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: soulfind-${{ matrix.arch }}-linux-${{ matrix.type }}
          path: bin
