# SPDX-FileCopyrightText: 2024 Soulfind Contributors
# SPDX-License-Identifier: GPL-3.0-or-later

name: CI

on: [push, pull_request]

jobs:

  build:
    timeout-minutes: 15
    strategy:
      matrix:
        os: [linux-x86_64, macos-arm64, macos-x86_64, windows-x86_64]
        compiler: [ldc, dmd, gdc]
        type: [release, debug]
        include:
          - os: linux-x86_64
            image: ubuntu-latest
            container: alpine:edge

          - os: macos-arm64
            image: macos-latest
            target: 11

          - os: macos-x86_64
            image: macos-13
            target: 10.12

          - os: windows-x86_64
            image: windows-latest

          - os: linux-x86_64
            compiler: ldc
            dflags: -static

          - compiler: ldc
            package: ldc

          - compiler: dmd
            package: dmd

          - compiler: gdc
            package: gcc-gdc

          - type: debug
            flags: --debug=db --debug=msg --debug=user
        exclude:
          - os: macos-arm64
            compiler: dmd

          - os: macos-arm64
            compiler: gdc

          - os: macos-x86_64
            compiler: gdc

          - os: windows-x86_64
            compiler: gdc
    runs-on: ${{ matrix.image }}
    container: ${{ matrix.container }}
    env:
      DFLAGS: ${{ matrix.dflags }}
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.target }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up D
        if: runner.os != 'Linux'
        uses: dlang-community/setup-dlang@v2
        with:
          compiler: ${{ matrix.compiler }}
          dub: latest

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: apk add ${{ matrix.package }} clang19 dub musl-dev

      - name: test
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build
        run: dub build --build=${{ matrix.type }} ${{ matrix.flags }}

      - name: Ad-hoc signing
        if: runner.os == 'macOS'
        run: codesign -s - bin/*

      - name: Archive artifacts
        if: matrix.compiler == 'ldc'
        uses: actions/upload-artifact@v4
        with:
          name: soulfind-${{ matrix.os }}-${{ matrix.type }}
          path: bin

  reuse-compliance:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: REUSE compliance
        uses: fsfe/reuse-action@v5
