# SPDX-FileCopyrightText: 2025 Soulfind Contributors
# SPDX-License-Identifier: GPL-3.0-or-later

name: Container
on: [push, pull_request]
permissions:
  packages: write
env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build:
    timeout-minutes: 15
    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            image: ubuntu-latest

          - arch: arm64
            image: ubuntu-24.04-arm
    runs-on: ${{ matrix.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: docker build -t $IMAGE_NAME:latest-${{ matrix.arch }} .

      - name: Save image
        run: docker save -o soulfind-image-${{ matrix.arch }}.tar $IMAGE_NAME:latest-${{ matrix.arch }}

      - name: Push image
        if: github.ref == 'refs/heads/master'
        run: |
          echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push $IMAGE_NAME:latest-${{ matrix.arch }}

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: soulfind-image-${{ matrix.arch }}
          path: soulfind-image-${{ matrix.arch }}.tar

  manifest:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Create manifest
        run: |
          echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker buildx imagetools create --tag $IMAGE_NAME:latest $IMAGE_NAME:latest-amd64 $IMAGE_NAME:latest-arm64
